name: Update Activity Log

on:
  schedule:
    - cron: '0 0 * * *'   # 每天 00:00 UTC
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: activity-log
  cancel-in-progress: true

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Update recent activity into README
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: "lcyuu93"
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
          # 可選參數：
          # EVENT_LIMIT: 10
          # OUTPUT_STYLE: MARKDOWN
          # README_PATH: README.md
